In [3]:
import matplotlib
%matplotlib tk
%autosave 180
%load_ext autoreload
%autoreload 2

import nest_asyncio
%config Completer.use_jedi = False

#
import matplotlib.pyplot as plt
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# 
import numpy as np
import os
import scipy

# add root directory to be able to import packages
# todo: make all packages installable so they can be called/imported by environment
import sys
module_path = os.path.abspath(os.path.join('..'))
sys.path.append(module_path)

from utils.calcium import calcium
from utils.wheel import wheel
from utils.cohort import cohort 

Autosaving every 180 seconds


<ipython-input-3-e3b2feee25f7>:12: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML


/home/cat/.conda/envs/donato/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [19]:
#################################################
########## PDAYS OF RECORDINGS - PUPS ###########
#################################################

#
root_dir = '/media/cat/4TB/donato/'

#
mouse_ids = [
    'DON-006084',
    'DON-006085',
    'DON-006087',
     'DON-002865',   #P90
     'DON-003165',   #P120
     'DON-003343',   #P150

#     #'DON-009191',
    #'DON-009192',
    #'DON-010473',
    #'DON-010477',
    
    
        
#     'DON-002865',   P90
#     'DON-003165',   P120
#     'DON-003343',   P150
    
#     'DON-008497',   P60
#     'DON-008498',   P60
#     'DON-008499',   P60
       
    
    
    
]

#
PDays = [
    [19,28],
    [19,28],
    [24,33],
    [90,99],
    [120,129],
    [150,159],



   # [16,48],  # expression issues
   # [15,60],  
   # [16,33],
   # [15,33],
    
    

    
    
]

#
coh = cohort.Cohort(mouse_ids, 
                    PDays,
                    wheel.Wheel)

coh.root_dir = root_dir



In [20]:

coh.plot_recording_summary()


In [57]:
#################################################
############ # of CELLS PER RECORDING ###########
#################################################
# 
coh.show_n_cell_allmice()
#


[19 20 21 22 23 24 25 26 27 28]
[441, 521, 460, 562, 514, 259, 544, 322, 546, 400]
[19 20 21 22 23 24 25 26 27 28]
[1316, 1111, 460, 1603, 1191, 1173, 1128, 1015, 1027, 690]
[24 25 26 27 28 29 30 31 32 33]
[244, 418, 632, 573, 764, 1009, 1466, 1132, 962, 1121]
[90 91 92 93 94 95 96 97 98 99]
[1064, 748, 885, 827, 1177, 850, 769, 594, 876, 1079]
[120 121 122 123 124 125 126 127 128 129]
[657, 354, 337, 389, 399, 399, 305, 301, 321, 305]
[150 151 152 153 154 155 156 157 158 159]
[840, 842, 1084, 1023, 778, 542, 840, 882, 605, 519]


In [37]:
##############################################################
##############################################################
##############################################################

#
coh.show_n_frames_allmice()


In [52]:
##############################################################
##############################################################
##############################################################

coh.show_distance_travelled_allmice()

loading mice: 100%|██████████| 6/6 [00:07<00:00,  1.28s/it]


In [54]:
##############################################################
##############################################################
##############################################################

#
coh.show_time_spent_running_allmice()

missing data for DON-002865_202102112
missing data for DON-003343_20210221


In [36]:
F = np.load('/media/cat/4TB1/donato/DON-009191/20220223/002P-F/tif/suite2p/plane0/F.npy')
print (F.shape)

idx = np.load('/media/cat/4TB1/donato/DON-009191/20220223/002P-F/tif/suite2p/plane0/iscell.npy')
print (np.where(idx==1.0)[0].shape)

(632, 111496)
(427,)
